# Site settings
title: "Lukas' Blog"
email: lukas.kalbertodt@gmail.com
description: "A blog about programming, Rust, typography, language and stuff."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lukaskalbertodt.github.io" # the base hostname & protocol for your site
github_username: LukasKalbertodt

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
